trigger:
  - master

resources:
  - repo: self

variables:
  tag: latest
  dockerId: simogasp  # your Docker ID for Docker Hub
  imageName: eesep-dependencies  # the name of the image you want to publish

stages:
  - stage: Build
    displayName: Build image
    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          command: login
          containerRegistry: dockerHub
      - task: Docker@2
        displayName: Build and Push
        inputs:
         command: buildAndPush
         arguments: NPROC=2
         repository: $(dockerId)/$(imageName)
         tags: |
           $(tag)